import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Cinzel_Decorative } from 'next/font/google'

const cinzel = Cinzel_Decorative({
  variable: '--font-cinzel',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: "Psychological Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cinzel.variable}`}>
      <body className="font-[var(--font-cinzel)]">
        {children}
      </body>
    </html>
  );
}
