import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Jacques_Francois } from 'next/font/google'

const jacques = Jacques_Francois({
  variable: '--font-jacques',
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: "Psychological Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jacques.variable} ${jacques.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
